services:
  web:
    build: .
    container_name: volatility_web
    hostname: volatility_web
    restart: unless-stopped
    ports:
      - "8080:3000"
    environment:
      - TZ=Asia/Seoul
    networks:
      - server-base-net
    env_file:
      - .env

networks:
  server-base-net:
    external: true
